import { Company } from '@/lib/types/companies';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Tech Solutions Ltda',
    cnpj: '12.345.678/0001-90',
    corporate_name: 'Tech Solutions Desenvolvimento de Software Ltda',
    phone: '(11) 3456-7890',
    email: 'contato@techsolutions.com.br',
    address: 'Av. Paulista, 1000',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '01310-100',
    logo_url: '/logos/tech-solutions.png',
    industry: 'technology',
    monthly_revenue_range: 1000000,
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-10-24T09:15:00Z',
    active: true,
    created_by: 'user1'
  },
  {
    id: '2',
    name: 'Comércio Central S/A',
    cnpj: '23.456.789/0001-00',
    corporate_name: 'Comércio Central de Produtos S/A',
    phone: '(21) 2345-6789',
    email: 'sac@comerciocentral.com.br',
    address: 'Rua do Comércio, 500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zip_code: '20040-020',
    industry: 'retail',
    monthly_revenue_range: 500000,
    created_at: '2024-02-01T14:20:00Z',
    updated_at: '2024-10-23T16:45:00Z',
    active: true,
    created_by: 'user1'
  },
  {
    id: '3',
    name: 'Serviços Profissionais ME',
    cnpj: '34.567.890/0001-10',
    corporate_name: 'Serviços Profissionais de Consultoria ME',
    phone: '(31) 3456-7890',
    email: 'contato@servicospro.com.br',
    address: 'Rua da Bahia, 1200',
    city: 'Belo Horizonte',
    state: 'MG',
    zip_code: '30160-011',
    industry: 'services',
    monthly_revenue_range: 50000,
    created_at: '2024-03-10T09:00:00Z',
    updated_at: '2024-10-22T14:20:00Z',
    active: true,
    created_by: 'user1'
  },
  {
    id: '4',
    name: 'Indústria de Componentes SA',
    cnpj: '45.678.901/0001-23',
    corporate_name: 'Indústria de Componentes Eletrônicos SA',
    phone: '(51) 3456-7890',
    email: 'vendas@componentesind.com.br',
    address: 'Av. Industrial, 3000',
    city: 'Porto Alegre',
    state: 'RS',
    zip_code: '90220-000',
    industry: 'manufacturing',
    monthly_revenue_range: 2000000,
    created_at: '2024-04-05T11:30:00Z',
    updated_at: '2024-10-21T10:30:00Z',
    active: true,
    created_by: 'user1'
  },
  {
    id: '5',
    name: 'Construtura e Obras Ltda',
    cnpj: '56.789.012/0001-45',
    corporate_name: 'Construtura e Obras Civis Ltda',
    phone: '(61) 3456-7890',
    email: 'orcamento@construturaobras.com.br',
    address: 'SQS 104 Bloco A',
    city: 'Brasília',
    state: 'DF',
    zip_code: '70330-000',
    industry: 'construction',
    monthly_revenue_range: 300000,
    created_at: '2024-05-20T16:00:00Z',
    updated_at: '2024-10-20T15:45:00Z',
    active: true,
    created_by: 'user1'
  },
  {
    id: '6',
    name: 'Consultoria Financeira Inativa',
    cnpj: '67.890.123/0001-67',
    corporate_name: 'Consultoria Financeira e Assessoria Ltda',
    phone: '(41) 3456-7890',
    email: 'inativo@consultoriafina.com.br',
    address: 'Rua XV de Novembro, 1500',
    city: 'Curitiba',
    state: 'PR',
    zip_code: '80060-000',
    industry: 'consulting',
    monthly_revenue_range: 80000,
    created_at: '2023-12-01T13:00:00Z',
    updated_at: '2024-08-15T10:30:00Z',
    active: false,
    created_by: 'user1'
  }
];

export const states = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' }
];